"""Initial Migration

Revision ID: 742b1adeb345
Revises: 
Create Date: 2024-04-25 10:47:03.914087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742b1adeb345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_distributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users_customers.id'], name=op.f('fk_customer_products_customer_id_users_customers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers_distributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distributor_name', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('distributor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users_customers.id'], name=op.f('fk_customers_distributors_customer_id_users_customers')),
    sa.ForeignKeyConstraint(['distributor_id'], ['users_distributors.id'], name=op.f('fk_customers_distributors_distributor_id_users_distributors')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('distributor_product_name', sa.String(), nullable=True),
    sa.Column('distributor_product_size', sa.String(), nullable=True),
    sa.Column('distributor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['users_distributors.id'], name=op.f('fk_distributor_prices_distributor_id_users_distributors')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_orders_placed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_product_name', sa.String(), nullable=True),
    sa.Column('date_ordered', sa.DateTime(), nullable=True),
    sa.Column('qty_ordered', sa.Integer(), nullable=True),
    sa.Column('ordered_from_distributor_name', sa.String(), nullable=True),
    sa.Column('ordered_from_distributor_product_name', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['customer_products.id'], name=op.f('fk_customer_orders_placed_product_id_customer_products')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_orders_placed')
    op.drop_table('distributor_prices')
    op.drop_table('customers_distributors')
    op.drop_table('customer_products')
    op.drop_table('users_distributors')
    op.drop_table('users_customers')
    # ### end Alembic commands ###
