"""added the password into users tables

Revision ID: d9654ced54eb
Revises: 4df11a92f9df
Create Date: 2024-04-27 09:47:56.666957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9654ced54eb'
down_revision = '4df11a92f9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))

    with op.batch_alter_table('users_distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_distributors', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('users_customers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
