"""empty message

Revision ID: fa810789f27e
Revises: d9654ced54eb
Create Date: 2024-04-27 09:57:28.968336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa810789f27e'
down_revision = 'd9654ced54eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))

    with op.batch_alter_table('users_distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_distributors', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('users_customers', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
